/////////////////////////////////////////////////////////////////////////////
// ADMIN SETTINGS ////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////
module.exports = {
  CONFIG_ADMIN_DEFAULT_TAB_NAME: "Catches",
  CONFIG_ADMIN_DEFAULT_TAB_NAME_LIST: [
    "Anglers",
    "Sponsors",
    "Catches",
    "Announcements",
    "Pots",
    // "Auction",
    "Stats",
    "Reports",
  ],
  CONFIG_ADMIN_TOURNAMENT_START_DATE_STRING: "2024-07-11",
  // CONFIG_ADMIN_TOURNAMENT_START_DATE_STRING: "2024-07-17",
  CONFIG_ADMIN_TOURNAMENT_END_DATE_STRING: "2024-07-14",
  // CONFIG_ADMIN_TOURNAMENT_END_DATE_STRING: "2024-07-20",
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_ANGLERS: [
    {
      field: "anglerId",
      headerName: "Angler ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "anglerName",
      headerName: "Angler",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "boatName",
      headerName: "Boat Name",
      type: "string",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "division",
      headerName: "Division",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "gender",
      headerName: "Gender",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "ageBracket",
      headerName: "Age",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "hometown",
      headerName: "Hometown",
      type: "string",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "sponsorName",
      headerName: "Sponsor",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "over21",
      headerName: "Over 21?",
      type: "boolean",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "email",
      headerName: "Email",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: false,
      flex: 4,
      width: 400,
      isId: false,
      isPhoneNumber: false,
      isCurrency: false,
      isEmail: true,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "phone",
      headerName: "Phone",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: false,
      flex: 4,
      width: 400,
      isId: false,
      isPhoneNumber: true,
      isCurrency: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "registrationTimestamp",
      headerName: "Time of Registration",
      type: "dateTime",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: true,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "hasCheckedIn",
      headerName: "Checked-In?",
      type: "boolean",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "paymentStatus",
      headerName: "Payment Status",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "registrationFee",
      headerName: "Registration Fee ($)",
      type: "number",
      isEditable: false,
      isRequired: false,
      isVisible: false,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
  ],
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_SPONSORS: [
    {
      field: "sponsorId",
      headerName: "Sponsor ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "sponsorName",
      headerName: "Name",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "email",
      headerName: "Email",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 4,
      width: 400,
      isId: false,
      isPhoneNumber: false,
      isCurrency: false,
      isEmail: true,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "phone",
      headerName: "Phone",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 4,
      width: 400,
      isId: false,
      isPhoneNumber: true,
      isCurrency: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalFee",
      headerName: "Total Donated",
      type: "number",
      isEditable: false,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "registrationTimestamp",
      headerName: "Time of Registration",
      type: "dateTime",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: true,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "logoUrl",
      headerName: "Logo",
      type: "image",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      valueFormatter: null,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: true,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "paymentStatus",
      headerName: "Payment Status",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
  ],
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_CATCHES: [
    {
      field: "catchId",
      headerName: "Catch ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "anglerId",
      headerName: "Angler ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "species",
      headerName: "Species",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isPhoneNumber: false,
      isCurrency: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "division",
      headerName: "Division",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "type",
      headerName: "Type",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isPhoneNumber: false,
      isCurrency: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "anglerName",
      headerName: "Angler",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "weight",
      headerName: "Weight (lbs)",
      type: "number",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "length",
      headerName: "Length (in)",
      type: "number",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "girth",
      headerName: "Girth (in)",
      type: "number",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "points",
      headerName: "Points",
      type: "number",
      isEditable: false,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "dateTime",
      headerName: "Time of Catch",
      type: "dateTime",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: true,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
  ],
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_ANNOUNCEMENTS: [
    {
      field: "announcementId",
      headerName: "ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 1,
      width: 200,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "subject",
      headerName: "Subject",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 1,
      width: 200,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },    
    {
      field: "subtitle",
      headerName: "Message",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 1,
      width: 200,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },    
    {
      field: "hyperlink",
      headerName: "Hyperlink",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 1,
      width: 200,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },    
    {
      field: "timestamp",
      headerName: "Time Created",
      type: "dateTime",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 1,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: true,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },    
  ],
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_POTS: [
    {
      field: "potId",
      headerName: "Pot ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "name",
      headerName: "Angler (or Team)",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "board",
      headerName: "Board",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalCatch&ReleaseFee",
      headerName: "Catch & Release Fee",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalOffshoreFee",
      headerName: "Offshore Fee",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalBaySurfFee",
      headerName: "Bay/Surf Fee",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalPotFee",
      headerName: "Total Fee",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "boardSelections",
      headerName: "Board Selections",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
  ],
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_AUCTIONS: [],
};

