/////////////////////////////////////////////////////////////////////////////
// CATCH SETTINGS ///////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////
module.exports = {
  CONFIG_CATCHES_STATS_LIST: [
    "Catch & Release", 
    "Offhsore",
    "Bay/Surf",
    "Flyfish",
    "Kayak"
  ],
  CONFIG_CATCHES_SPECIES_LIST: [

    // Catch & Release
    {
      label: "Blue Marlin",
      category: "Catch & Release",
      points: 400,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      label: "White Marlin",
      category: "Catch & Release",
      points: 100,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      label: "Sailfish",
      category: "Catch & Release",
      points: 70,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },

    // Offshore
    {
      label: "Barracuda",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Blackfin Tuna",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Dolphin (Dorado Mahi)",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Jack Crevalle (Jackfish)",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "King Mackerel (Kingfish)",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Ling (Cobia)",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Blacktip/Spinner Shark",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Wahoo",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Spanish Mackerel",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Yellowfin Tuna",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Red Snapper",
      category: "Offshore",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },

    // Bay/Surf
    {
      label: "Black Drum",
      category: "Bay/Surf",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Flounder",
      category: "Bay/Surf",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Gafftop",
      category: "Bay/Surf",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Pompano",
      category: "Bay/Surf",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Redfish",
      category: "Bay/Surf",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Speckled Trout",
      category: "Bay/Surf",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      label: "Spanish Mackerel",
      category: "Bay/Surf",
      points: 1,
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },

    // Flyfish
    { 
      label: "Redfish", 
      category: "Flyfish", 
      points: 1, 
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: true,
      photoIsRequired: true,
    },
    { 
      label: "Speckled Trout", 
      category: "Flyfish", 
      points: 1, 
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },

    // Kayak
    { 
      label: "Redfish", 
      category: "Kayak", 
      points: 1, 
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: true,
      photoIsRequired: true,
    },
    { 
      label: "Speckled Trout", 
      category: "Kayak", 
      points: 1, 
      pointsCalculationMethod: "weightRoundDown",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },

  ],
};

