/////////////////////////////////////////////////////////////////////////////
// ADMIN SETTINGS ////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////
module.exports = {
  CONFIG_ADMIN_DEFAULT_TAB_NAME: "Catches",
  CONFIG_ADMIN_DEFAULT_TAB_NAME_LIST: [
    "Teams",
    "Catches",
    "Announcements",
    "Pots",
    // "Auction",
    "Stats",
    "Reports",
  ],
  // CONFIG_ADMIN_TOURNAMENT_START_DATE_STRING: "2025-07-16",
  CONFIG_ADMIN_TOURNAMENT_START_DATE_STRING: "2024-07-17",
  // CONFIG_ADMIN_TOURNAMENT_END_DATE_STRING: "2025-07-19",
  CONFIG_ADMIN_TOURNAMENT_END_DATE_STRING: "2024-07-20",
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_TEAMS: [
    // Standard
    {
      field: "teamId",
      headerName: "Team ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "teamName",
      headerName: "Team",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "isEarlybird",
      headerName: "Earlybird?",
      type: "boolean",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "teamEmail",
      headerName: "Email",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 4,
      width: 400,
      isId: false,
      isPhoneNumber: false,
      isCurrency: false,
      isEmail: true,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "teamPhone",
      headerName: "Phone",
      type: "string",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isPhoneNumber: true,
      isCurrency: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "teamCardholderName",
      headerName: "Cardholder Name",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "teamPaymentStatus",
      headerName: "Has Paid",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalFeePaidAtCheckout",
      headerName: "Total Fee ($)",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "hasCheckedIn",
      headerName: "Checked-In?",
      type: "boolean",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "registrationFee",
      headerName: "Registration Fee ($)",
      type: "number",
      isEditable: false,
      isRequired: false,
      isVisible: false,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "registrationTimestampInLocalTime",
      headerName: "Time of Registration",
      type: "dateTime",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: true,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    // Required images
    {
      field: "Team Photo",
      headerName: "Team Photo",
      type: "image",
      isEditable: true,
      isRequired: true,
      isVisible: false,
      flex: 2,
      width: 200,
      valueFormatter: null,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: true,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    // Unrequired images
    {
      field: "Captain Photo",
      headerName: "Captain Photo",
      type: "image",
      isEditable: true,
      isRequired: false,
      isVisible: false,
      flex: 2,
      width: 200,
      valueFormatter: null,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: true,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    // Add on charges
    {
      field: "Extra Wristbands",
      headerName: "# Extra Wristbands",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      valueFormatter: null,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: true,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "T-shirts",
      headerName: "# T-shirts",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      valueFormatter: null,
      isId: false,
      isPhoneNumber: false,
      isCurrency: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: true,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
  ],
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_CATCHES: [
    {
      field: "catchId",
      headerName: "Catch ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "teamId",
      headerName: "Team ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "species",
      headerName: "Species",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isPhoneNumber: false,
      isCurrency: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "speciesType",
      headerName: "Type",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isPhoneNumber: false,
      isCurrency: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "teamName",
      headerName: "Team",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "weight",
      headerName: "Weight (lbs)",
      type: "number",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "length",
      headerName: "Length (in)",
      type: "number",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "girth",
      headerName: "Girth (in)",
      type: "number",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "points",
      headerName: "Points",
      type: "number",
      isEditable: false,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "dateTime",
      headerName: "Time of Catch",
      type: "dateTime",
      isEditable: true,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: true,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    // Images
    {
      field: "catchPhoto",
      headerName: "Photo",
      type: "image",
      isEditable: true,
      isRequired: false,
      isVisible: true,
      flex: 2,
      width: 200,
      valueFormatter: null,
      isId: false,
      isCurrency: false,
      isPhoneNumber: true,
      isEmail: false,
      isDateTime: false,
      isImage: true,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
  ],
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_ANNOUNCEMENTS: [
    {
      field: "announcementId",
      headerName: "ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 1,
      width: 200,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "subject",
      headerName: "Subject",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 1,
      width: 200,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },    
    {
      field: "subtitle",
      headerName: "Message",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 1,
      width: 200,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },    
    {
      field: "hyperlink",
      headerName: "Hyperlink",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 1,
      width: 200,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },    
    {
      field: "timestamp",
      headerName: "Time Created",
      type: "dateTime",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 1,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: true,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },    
  ],
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_POTS: [
    {
      field: "potId",
      headerName: "Pot ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "teamId",
      headerName: "Team ID",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 3,
      width: 300,
      isId: true,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "teamName",
      headerName: "Team",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 3,
      width: 300,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalCaptain&MateFee",
      headerName: "Captain & Mate Fee",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalBillfishFee",
      headerName: "Billfish Fee",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalMeatfishFee",
      headerName: "Meatfish Fee",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "totalPotFee",
      headerName: "Total Fee",
      type: "number",
      isEditable: false,
      isRequired: true,
      isVisible: true,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: true,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
    {
      field: "boardSelections",
      headerName: "Board Selections",
      type: "string",
      isEditable: false,
      isRequired: true,
      isVisible: false,
      flex: 2,
      width: 200,
      isId: false,
      isCurrency: false,
      isPhoneNumber: false,
      isEmail: false,
      isDateTime: false,
      isImage: false,
      isAddOnCharge: false,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
      align: "center",
    },
  ],
  CONFIG_ADMIN_TABLE_PROPERTIES_FOR_AUCTIONS: [],
};

