/////////////////////////////////////////////////////////////////////////////
// STYLE SETTINGS ///////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////
module.exports = {

  // GENERAL
  CONFIG_STYLING_BANNER_BACKGROUND_COLOR: '#7FADCD',
  CONFIG_STYLING_BANNER_TEXT_COLOR: 'white',
  CONFIG_STYLING_SECTION_BACKGROUND_COLOR: 'white',
  CONFIG_STYLING_SECTION_TEXT_COLOR: 'black',
  CONFIG_STYLING_H1_COLOR: 'white',
  CONFIG_STYLING_H2_COLOR: '#004B8C',
  CONFIG_STYLING_H3_COLOR: '#004B8C',
  CONFIG_STYLING_P_COLOR: '#004B8C',

  // TABLES
  CONFIG_STYLING_TABLE_HEADER_BACKGROUND_COLOR: '#7FADCD',
  CONFIG_STYLING_TABLE_HEADER_TEXT_COLOR: 'white',
  CONFIG_STYLING_TABLE_ODD_ROW_BACKGROUND_COLOR: 'rgb(234,234,234)',
  CONFIG_STYLING_TABLE_CELL_TEXT_COLOR: '#222222',

  // NAVBAR
  CONFIG_STYLING_NAVBAR_BACKGROUND_COLOR: 'white',
  CONFIG_STYLING_NAVBAR_TEXT_COLOR: '#222222',

  // BUTTONS
  CONFIG_STYLING_BUTTON_BORDER_COLOR: 'black',
  CONFIG_STYLING_BUTTON_BACKGROUND_COLOR: '#004B8C',
  CONFIG_STYLING_BUTTON_TEXT_COLOR: 'white',

  // HOME
  CONFIG_STYLING_HOME_HERO_BACKGROUND_COLOR: '#7FADCD',
  CONFIG_STYLING_HOME_HERO_TEXT_COLOR: '#004B8C',
  CONFIG_STYLING_HOME_INFO_BACKGROUND_COLOR: 'white',
  CONFIG_STYLING_HOME_INFO_TEXT_COLOR: '#004B8C',
  CONFIG_STYLING_HOME_INFO_HIGHLIGHTED_TEXT_COLOR: 'orange',

  // REGISTER
  CONFIG_STYLING_REGISTER_TITLE_TEXT_COLOR: '#756145',
  CONFIG_STYLING_REGISTER_SUBTITLE_TEXT_COLOR: '#004B8C',

  // ADMIN
  CONFIG_STYLING_LOGIN_TEXT_COLOR: '#004B8C',
  CONFIG_STYLING_STATS_TEXT_COLOR: '#004B8C',
  CONFIG_STYLING_ADMIN_TOOLBAR_TEXT_COLOR: '#004B8C',

  // LEADERBOARD
  CONFIG_STYLING_LEADERBOARD_TIMESTAMP_TEXT_COLOR: '#004B8C',
  CONFIG_STYLING_LEADERBOARD_TITLE_TEXT_COLOR: '#004B8C',
  CONFIG_STYLING_LEADERBOARD_SUBTITLE_TEXT_COLOR: 'red',
  CONFIG_STYLING_LEADERBOARD_SUBTITLE_FONT_STYLE: 'italic',

  // POTS
  CONFIG_STYLING_POTS_TIMESTAMP_TEXT_COLOR: '#004B8C',
  CONFIG_STYLING_POTS_TITLE_TEXT_COLOR: '#004B8C',
  CONFIG_STYLING_POTS_SUBTITLE_TEXT_COLOR: 'red',
  CONFIG_STYLING_POTS_SUBTITLE_FONT_STYLE: 'italic',
  CONFIG_STYLING_POTS_WINNER_ROW_BACKGROUND_COLOR: '#dddddd',
  CONFIG_STYLING_POTS_LOSER_ROW_BACKGROUND_COLOR: 'white',
  CONFIG_STYLING_POTS_ROW_TEXT_COLOR: '#2C2C2C',

  // DASHBOARD
  CONFIG_STYLING_DASHBOARD_TITLE_TEXT_COLOR: 'black',

  // NEWSFEED...
  // AUCTION...
  // TOGGLES...
  // COUNTDOWNS...
  // MODALS...

  // FOOTER
  CONFIG_STYLING_FOOTER_BACKGROUND_COLOR: "#222222",
  CONFIG_STYLING_FOOTER_TEXT_COLOR: "#fffff",
  CONFIG_STYLING_FOOTER_SECTION_DIVIDER_COLOR: "#333333",
  CONFIG_STYLING_FOOTER_SECTION_DIVIDER_HIGHLIGHT_COLOR: "#7FADCD",

};

