/////////////////////////////////////////////////////////////////////////////
// CATCH SETTINGS ///////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////
export default {
  CONFIG_CATCHES_STATS_LIST: [
    "Offshore",
    "Bay/Surf",
    "Flyfishing",
    "Kayak"
  ],
  CONFIG_CATCHES_SPECIES_LIST: [
    // Offshore
    {
      species: "Blue Marlin",
      division: "Offshore",
      type: "Billfish",
      points: 400,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      species: "White Marlin",
      division: "Offshore",
      type: "Billfish",
      points: 100,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      species: "Sailfish",
      division: "Offshore",
      type: "Billfish",
      points: 70,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      species: "Tarpon",
      division: "Offshore",
      type: "Billfish",
      points: 1,
      pointsCalculationMethod: "flat",
      weightIsRequired: false,
      lengthIsRequired: false,
      girthIsRequired: false,
      dateTimeIsRequired: true,
      photoIsRequired: false,
    },
    {
      species: "Barracuda",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Blackfin Tuna",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Bonito (Little Tunny)",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Dolphin (Dorado Mahi)",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Jack Crevalle (Jackfish)",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "King Mackerel (Kingfish)",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Ling (Cobia)",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Blacktip/Spinner Shark",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Wahoo",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Spanish Mackerel",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Yellowfin Tuna",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Red Snapper",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },

    // Bay/Surf
    {
      species: "Black Drum",
      division: "Bay/Surf",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Bonito (Little Tunny)",
      division: "Bay/Surf",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Flounder",
      division: "Bay/Surf",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Gafftop",
      division: "Bay/Surf",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Pompano",
      division: "Bay/Surf",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Redfish",
      division: "Bay/Surf",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Speckled Trout",
      division: "Bay/Surf",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Spanish Mackerel",
      division: "Bay/Surf",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },

    // Flyfish
    { 
      species: "Redfish", 
      division: "Flyfishing", 
      type: "Meatfish",
      points: 1, 
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    { 
      species: "Speckled Trout", 
      division: "Flyfishing", 
      type: "Meatfish",
      points: 1, 
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },

    // Kayak
    { 
      species: "Redfish", 
      division: "Kayak", 
      type: "Meatfish",
      points: 1, 
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },
    {
      species: "Speckled Trout",
      division: "Kayak",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },

    {
      species: "Swordfish",
      division: "Offshore",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: true,
      photoIsRequired: true,
    },

    // Bay/Surf
    {
      species: "Sheepshead",
      division: "Bay/Surf",
      type: "Meatfish",
      points: 1,
      pointsCalculationMethod: "weightExact",
      weightIsRequired: true,
      lengthIsRequired: true,
      girthIsRequired: true,
      dateTimeIsRequired: false,
      photoIsRequired: false,
    },

  ],
};

